"""This module records filenames and mappings from config strings to functions."""

DATASET_DIRNAME = "datasets"
TRAIN_DATASET_DIRNAME = "%s/v3.2/train" % DATASET_DIRNAME
SUBTASK_B_TRAIN2016_DATASET_FNAMES = \
    ["%s/SemEval2016-Task3-CQA-QL-train-part1.xml" % TRAIN_DATASET_DIRNAME,
     "%s/SemEval2016-Task3-CQA-QL-train-part2.xml" % TRAIN_DATASET_DIRNAME]
DEV_DATASET_DIRNAME = "%s/v3.2/dev" % DATASET_DIRNAME
DEV_DATASET_FNAME = "%s/SemEval2016-Task3-CQA-QL-dev.xml" % DEV_DATASET_DIRNAME
TEST2016_DATASET_DIRNAME = "%s/SemEval2016_task3_test/English" % DATASET_DIRNAME
TEST2016_DATASET_FNAME = "%s/SemEval2016-Task3-CQA-QL-test.xml" % TEST2016_DATASET_DIRNAME
SUBTASK_B_TRAIN2017_DATASET_FNAMES = SUBTASK_B_TRAIN2016_DATASET_FNAMES + [TEST2016_DATASET_FNAME]
TEST2016_DIRNAME = "%s/SemEval2016_task3_submissions_and_scores" % DATASET_DIRNAME
TEST2017_DATASET_DIRNAME = "%s/SemEval2017_task3_test_input_ABCD/English-ABC" % DATASET_DIRNAME
TEST2017_DATASET_FNAME = "%s/SemEval2017-task3-English-test-input.xml" % TEST2017_DATASET_DIRNAME
TEST2017_DIRNAME = "%s/SemEval2017_task3_submissions_and_scores" % DATASET_DIRNAME
SUBTASK_A_TRAIN_DATASET_FNAMES = \
    ["%s/SemEval2016-Task3-CQA-QL-train-part1-subtaskA.xml" % TRAIN_DATASET_DIRNAME,
     "%s/SemEval2016-Task3-CQA-QL-train-part2-subtaskA.xml" % TRAIN_DATASET_DIRNAME,
     "%s/SemEval2016-Task3-CQA-QL-test-subtaskA.xml" % TEST2016_DATASET_DIRNAME,
     "%s/SemEval2017-task3-English-test-subtaskA-input.xml" % TEST2017_DATASET_DIRNAME]
TEST_PREDICTIONS_BASE_DIRNAME = "RaRe"
TEST2016_PREDICTIONS_DIRNAME = "%s/%s" % (TEST2016_DIRNAME, TEST_PREDICTIONS_BASE_DIRNAME)
TEST2017_PREDICTIONS_DIRNAME = "%s/%s" % (TEST2017_DIRNAME, TEST_PREDICTIONS_BASE_DIRNAME)
DEV_GOLD_BASE_FNAME = "../SemEval2016-Task3-CQA-QL-dev.xml.subtaskB.relevancy"
TEST2016_GOLD_BASE_FNAME = "_gold/SemEval2016-Task3-CQA-QL-test.xml.subtaskB.relevancy"
TEST2017_GOLD_BASE_FNAME = "_gold/SemEval2017-Task3-CQA-QL-test.xml.subtaskB.relevancy"

ENWIKI_DATASET_BASE_FNAME="%s/enwiki-20171103-pages-articles-multistream" % DATASET_DIRNAME
ENWIKI_DATASET_CORPUS_FNAME="%s.xml.bz2" % ENWIKI_DATASET_BASE_FNAME
ENWIKI_DATASET_DICTIONARY_FNAME = "%s.dict" % ENWIKI_DATASET_BASE_FNAME
ENWIKI_DATASET_TFIDF_FNAME = "%s.tfidf" % ENWIKI_DATASET_BASE_FNAME
ENWIKI_DATASET_W2V_FNAME = "%s.w2v" % ENWIKI_DATASET_BASE_FNAME
ENWIKI_DATASET_TFIDF_MATRIX_FNAME = "%s.W" % ENWIKI_DATASET_BASE_FNAME

UNANNOTATED_DATASET_BASE_FNAME = "%s/QL-unannotated-data-subtaskA" % DATASET_DIRNAME
UNANNOTATED_DATASET_FNAME = "%s.xml" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_PRECOOKED_FNAME = "%s.pkl" % UNANNOTATED_DATASET_FNAME
UNANNOTATED_DATASET_DICTIONARY_FNAME = "%s.dict" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_DOCUMENT_TERM_MATRIX_FNAME = "%s.C" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_WEIGHTED_DOCUMENT_TERM_MATRIX_FNAME = "%s.WC" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_SOFT_WEIGHTED_DOCUMENT_TERM_MATRIX_FNAME = "%s.MWC" \
    % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_SOFT_MREL_MATRIX_FNAME = "%s.Mrel" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_SOFT_MLEV_MATRIX_FNAME = "%s.Mlev" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_SOFT_SVD_MATRIX_UT = "%s.Usoft" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_SOFT_SVD_MATRIX_S = "%s.Ssoft" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_SOFT_SVD_MATRIX_VT = "%s.Vsoft" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_SVD_MATRIX_UT = "%s.U" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_SVD_MATRIX_S = "%s.S" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_SVD_MATRIX_VT = "%s.V" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_TFIDF_FNAME = "%s.tfidf" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_TFIDF_MATRIX_FNAME = "%s.W" % UNANNOTATED_DATASET_BASE_FNAME
UNANNOTATED_DATASET_W2V_FNAME = "%s.w2v" % UNANNOTATED_DATASET_BASE_FNAME

EXTERNAL_TERM_SIMILARITY_MODEL_FILENAMES = {
    "w2v.googlenews": "%s/GoogleNews-vectors-negative300.bin.gz" % DATASET_DIRNAME,
    "glove.enwiki_gigaword5": "%s/glove.6B.300d.w2v" % DATASET_DIRNAME,
    "glove.common_crawl": "%s/glove.840B.300d.w2v" % DATASET_DIRNAME,
    "glove.twitter": "%s/glove.twitter.27B.200d.w2v" % DATASET_DIRNAME,
    "fasttext.enwiki": "%s/wiki.en.vec" % DATASET_DIRNAME}
